import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/app/providers";
import { Lexend, Red_Hat_Mono } from "next/font/google";
import { Tabs } from "@/components";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const lexendGiga = Lexend({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lexend",
});

export const redHatMono = Red_Hat_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-red-hat-mono",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`font-primary h-dvh bg-background overflow-hidden text-foreground gap-3 p-10 pt-15 ${lexendGiga.variable} ${redHatMono.variable}`}>
          
        <Tabs defaultValue="about" className='w-full h-full flex flex-row '>
          
     


        <QueryProvider>

              {children}
        </QueryProvider>
        </Tabs>
      </body>
    </html>
  );
}
